baseURL = ""
theme = "hugo-bearblog"
languageCode = "en-US"
enableRobotsTXT = true

title = "Eduardo's Blog"
author = "Eduardo Rittner Coelho"

[menus]
  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 10
  [[menus.main]]
    name = "Notes"
    pageRef = "/notes"
    weight = 20

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug/"

[params]
  description = "Eduardo's Blog"
  favicon = "images/favicon.png"
  title = "Eduardo's Blog"
  dateFormat = "2006-01-02"
  readMore = true
  toc = true
  tocWordCount = true
  mathjax = true

  [social]
