[package]
name = "pandalib"
version = "0.1.0"
edition = "2024"

[dependencies]
comrak = { version = "0.29.0", default-features = false, features = ["syntect"] }
walkdir = "2.5.0"
rss = "2.0.11"
chrono = "0.4.39"

