# Disabled for now since I'm not sure it's a good idea to use nightly on CI
#[build]
#rustflags = ["-Z", "threads=8"]

#[target.x86_64-unknown-linux-gnu]
#rustflags = ["-Zcodegen-backend=cranelift"]

