[package]
name = "panda"
version = "0.1.0"
edition = "2024"

[dependencies]
pandalib = {path = "./pandalib"}

[build]
rustflags = ["-Z", "threads=8"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Zcodegen-backend=cranelift"]

